
<head>
<style type="text/css">
.auto-style2 {
	color: #31C8F9;
}
</style>
</head>

<title>TS Computing - Service</title>
<p>WIR SIND BEREITS FÜR FOLGENDE FIRMEN IN 3<br />
VERSCHIEDENEN BEREICHEN FÜR SIE TÄTIG...</p><span class="auto-style7"><p>
<span class="auto-style4">
<span class="TS-STYLE_B2">
<br />
<span class="auto-style2"><strong>&bull; </strong> </span> </span>
<span class="auto-style12">ENTWICKLUNG</span><br />
<br />
	</span>
<span class="auto-style10">
<span class="auto-style12">DATENBANKEN</span></span></span><span class="auto-style8"><span class="auto-style10"><span class="auto-style15"> POSTGRESQL, MYSQL</span><span class="auto-style7"><br />
<span class="auto-style12">PROGRAMMIERSPRACHEN</span></span><span class="auto-style15"> PHP, 
		JSP, QB64</span><span class="auto-style7"><br />
<span class="auto-style12">WEB-ENTWICKLUNG</span></span><span class="auto-style15"> LOGIN, UI, CONTENT</span><br />
</span><span class="auto-style7"><br />
</p>
<p class="auto-style11">

</span><span class="auto-style4">
<span class="auto-style2">
<strong>&bull; </strong> </span>
<span class="auto-style7">
<span class="TS-CONTACT2">
<span class="auto-style12">SYSTEM ADMINISTRATION</span><br />
<br />

</span>

</span>
<span class="auto-style15">
<em>SOFTWARE INSTALLATION, 
		KONFIGURATION<br />
UND WARTUNG INKL. BACKUP</em></span><span class="auto-style7"><span class="TS-CONTACT2"><br />
<br />
<span class="auto-style12">BETRIEBSSYSTEME</span></span></span><span class="auto-style15"> DEBIAN, WINDOWS SERVER</span><span class="TS-CONTACT2"><span class="auto-style7"><br />
<span class="auto-style12">WEB-ENTWICKLUNG</span></span></span><span class="auto-style15"> LOGIN, UI, CONTENT</span><span class="auto-style7"><span class="TS-CONTACT2"><br />
<span class="auto-style12">WEBSERVER</span></span></span><span class="auto-style15"> APACHE2</span><br />
	</span>

<span class="auto-style7"><br />
</p>

</span></span>

<p class="auto-style4"><span class="auto-style2"><strong>&bull; </strong> </span>
<span class="auto-style12">NETZWERKSICHERHEIT</span><br />
<br />
<span class="auto-style12">VERSCHLÜSSELUNG</span><span class="auto-style15"> SSL, SSH</span><br />
<span class="auto-style12">WLAN</span><span class="auto-style15"> EINRICHTUNG UND KONFIGURATION<br></span><br />
</p>
<p class="auto-style4">TODO? <a href="https://www.linkedin.com/in/thomasschilb" target="_blank">THOMASSCHILB@LINKEDIN.COM</a></p>


