<title>TS Computing - Impressum</title>
<p>

<span class="auto-style7">
TS COMPUTING<br />
LYONER STR. 1<br />
60528, NIEDERRAD<br />
<br />
E-MAIL: 
<span class="TS-CONTACT1"> 
<a href="mailto:THOMASSCHILB@WEB.DE?subject=ABUSE" title="FEEL FREE TO SEND COMPLAINTS OR SUGGESTIONS FOR IMPROVEMENT">THOMASSCHILB@WEB.DE</a><br />
</span>STID-NR.: 67858029419<span class="TS-CONTACT1"><br />
</span></span></p>
<p><span class="auto-style7">
<span class="TS-CONTACT1">
<span class="TS-CONTACT2"><br />
WEBSITE</span><br />
<br />
</span>DIESES IMPRESSUM GILT FÜR ALLE ANGEBOTE UNTER DER DOMAIN<br>
<span class="TS-CONTACT1"> 
<a href="http://WWW.TSAG.IO">WWW.TSAG.IO</a>
</span>INKLUSIVE 
ALLER SUBDOMAINS (UNTERSEITEN).<span class="TS-CONTACT1"><br />
</span></span><span class="TS-CONTACT1"></p>
<p>
</span><span class="auto-style7">
<span class="TS-CONTACT1"><span class="TS-CONTACT2"><br />
SOZIALE MEDIEN</span><br />
<br />
</span>DIESES IMPRESSUM GILT AUCH FÜR UNSERE AUFTRITTE IN DEN<br>FOLGENDEN
SOZIALEN 
MEDIEN (ANGABEN GEMÄß § 5 TMG):<br />
<br />
LINKEDIN: <span class="TS-CONTACT1"> <a href="HTTPS://WWW.LINKEDIN.COM/IN/THOMASSCHILB/" title="TODO?">HTTPS://WWW.LINKEDIN.COM/IN/THOMASSCHILB/</a></span></span><span class="TS-CONTACT1"></p>
<p><span class="auto-style7">
<span class="TS-CONTACT2"><br />
BERUFLICHE ANGABEN</span><br />
</span>
</span><span class="auto-style7">
<br />
<span class="auto-style8">BERUFSBEZEICHNUNG: FREELANCER<br />
VERLIEHEN IN: DEUTSCHLAND<br />
BERUFSRECHTLICHE REGELUNGEN:
TRAINEE, FREELANCER</span></span><span class="TS-CONTACT1"><br />
</p>
<p><span class="auto-style7">
<span class="TS-CONTACT2"><br />
GÜLTIGKEIT</span><br />
<br />
</span>
</span><span class="auto-style7">
DIESES IMPRESSUM GILT AB DEM 17. OKTOBER 2023.<br />
</span></p>
<span class="TS-CONTACT1">
<p>
</span><span class="auto-style7">
<span class="TS-CONTACT1">
<span class="TS-CONTACT2"><br />
STREITBEILEGUNG</span><br />
<br />
</span>WIR BEMÜHEN UNS JEDERZEIT UM EIN EINVERNEHMEN MIT<br>DEM KUNDEN
NUTZEN SIE UNSEREN SERVICEKONTAKT<br>UNTER <span class="TS-CONTACT1"> <a href="mailto:THOMASSCHILB@WEB.DE">THOMASSCHILB@WEB.DE</a> </span>ODER UNSERE WEITEREN<br>ANGEGEBENEN KONTAKTMÖGLICHKEITEN.<span class="TS-CONTACT1"><br />
<br />
</span>DIE EUROPÄISCHE KOMMISSION STELLT EINE PLATTFORM<br>ZUR
ONLINE-STREITBEILEGUNG (OS) MIT WEITEREN<br>INFORMATIONEN ZUR
VERFÜGUNG,
DIE IM INTERNET UNTER:<span class="TS-CONTACT1"><br />
<br />
<a href="https://ec.europa.eu/consumers/odr/" target="_blank">
HTTPS://EC.EUROPA.EU/CONSUMERS/ODR/</a></span> ERREICHBAR IST.<span class="TS-CONTACT1"><br />
<br />
WIR SIND NICHT BEREIT UND NICHT VERPFLICHTET,<br>AN EINEM
STREITBEILEGUNGSVERFAHREN
VOR EINER<br />
VERBRAUCHERSCHLICHTUNGSSTELLE TEILZUNEHMEN.</span></span><span class="TS-CONTACT1"></p>
</span>


