<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<meta content="en-us" http-equiv="Content-Language" />
<title>TS | CODE</title>
<style type="text/css">
a {
	color: #808080;
	text-decoration: none;
}
a:visited {
	color: #808080;
}
a:active {
	color: #808080;
}
a:hover {
	color: #31C8F9;
}
table {
	font-family:'Roboto Mono Regular', monospace;
	}
}
pre {
	color: #31C8F9;
	}
}
.TS-STYLE_B1 {
	background-color: #333333;
}
.TS-STYLE_B2 {
	color: #31C8F9;
}
.TSIDX___1 {
	font-size: 18px;
}
.TSIDX___2 {
	color: #31C8F9;
	font-size: 18px;
}
.TSTAB_1 {
	font-weight: normal;
}
.TSTAB_2 {
	background-color: #181818;
}
.TSTAB_4 {
	background-color: #333333;
	text-align: right;
}
.TSTAB_5 {
	background-color: #333333;
	text-align: center;
}
.TSTAB_6 {
	background-color: #333333;
}
.TSTAB_7 {
	border-collapse: collapse;
	border: 1px solid #333333;
}
.auto-style3 {
	border-collapse: collapse;
	border: 1px solid #333333;
	font-family: "Roboto Mono Regular", monospace;
}
.auto-style4 {
	font-size: 18px;
	font-family: "Roboto Mono Regular", monospace;
}
.auto-style5 {
	font-family: "Roboto Mono Regular", monospace;
}
.auto-style6 {
	background-color: #181818;
	text-align: left;
}
.auto-style7 {
	color: #FFFFFF;
}
.auto-style8 {
	color: #00FF00;
}
.auto-style10 {
	background-color: #000000;
	text-align: right;
	font-size: 18px;
}
.auto-style11 {
	background-color: #000000;
}
.auto-style12 {
	background-color: #000000;
	text-align: right;
}
.auto-style13 {
	background-color: #000000;
	color: #31C8F9;
}
</style>
<meta content="TS, THOMAS, SCHILB, INDEX, PRIVATE, HOMEPAGE, REPOSITORY" name="keywords" />
<meta content="PRIVATE HOMEPAGE" name="description" />
<base target="_self" />
</head>

<body style="color: #808080; margin: 0; background-color: #151515">

<span class="TSIDX___2"><span class="auto-style5">&gt; CODE_</span><br /><br /><br />

</span>
<table cellpadding="7" cellspacing="0" style="width: 100%" class="auto-style3" align="center">
	<tr>
		<td class="auto-style11"><span class="TSIDX___2">BATCH</span></td>
		<td class="auto-style10">BAT / CMD</td>
	</tr>
	<tr>
		<td colspan="2" class="TSTAB_2">
		<span class="TSIDX___1"><span class="auto-style7">MY COLLECTION OF BATCH SCRIPTING</span><br />
		<br />
		<span class="auto-style7">DOCUMENTS<br />
		</span><br />
		BOOKS, REFERENCE<br />
		<br />
		<span class="auto-style7">SOURCECODE<br />
		</span><br />
		BATCHOGRAPHY, GITHUB, ETC.<br />
		<br />
		<br />
		<span class="auto-style7">BAT 2 EXE CONVERTER 3.2<br />
		</span><br />
		DESCRIPTION: BATCH-SCRIPTING IDE, WITH UPX COMPRESSION,<br />
		INTEGRATE MULTIPLE FILES, COMPILE TO ONE BINARY FILE<br />
		DOWNLOAD:
		<a href="./DL/TS-APPS/FREE/BAT.TO.EXE.CONVERTER.V3.2-TS.ZIP" target="_blank">LINK</a><br />
		<br />
		<span class="auto-style7">NOTEPAD++<br />
		</span><br />
		DESCRIPTION:
		A GOOD CODE-EDITOR IN PLAINTEXT<br />
		SITE: <a href="https://notepad-plus-plus.org/downloads/" target="_blank">
		LINK</a></span></td>
	</tr>
	<tr>
		<td colspan="2" class="TSTAB_5">
<a target="_blank" href="DL/ZIP/TS-CODE_BATCH.ZIP"><span class="TSIDX___1">DOWNLOAD</span></a> <span class="TSIDX___1">
		/ ZIP / 13 MB</span></td>
	</tr>
</table>
<span class="TSIDX___1">
<br class="auto-style5" />
<br class="auto-style5" />
<table cellpadding="7" cellspacing="0" style="width: 100%" class="auto-style3" align="center">
	<tr>
		<td class="auto-style13">PHP</td>
		<td class="auto-style12">&nbsp;</td>
	</tr>
<strong>
	<tr>
		<td colspan="2" class="TSTAB_2">
		<span class="auto-style7">MY COLLECTIONS OF PHP SCRIPTS</span><br />
		<span class="TSIDX___1"><br />
		<span class="auto-style7">SCRIPTS<br />
		</span><br />
		MY PHP SCRIPTS,
		BEST OF GITHUB<br />
		<br />
		<br />
		<span class="auto-style7">NOTEPAD++<br />
		</span><br />
		DESCRIPTION:
		A GOOD CODE-EDITOR IN PLAINTEXT<br />
		SITE: <a href="https://notepad-plus-plus.org/downloads/" target="_blank">
		LINK</a></span></td>
	</tr>
	<tr>
		<td colspan="2" class="TSTAB_5">
		<span class="TSIDX___1">
<a target="_blank" href="DL/ZIP/TS-CODE_PHP.ZIP">DOWNLOAD</a> / ZIP / 27 MB</span></td>
	</tr>
</table>
<br class="auto-style5" />
</strong>
</span><br class="auto-style4" />
<span class="TSIDX___1">
<table cellpadding="7" cellspacing="0" style="width: 100%" class="auto-style3" align="center">
	<tr>
		<td class="auto-style13">QB64</td>
		<td class="auto-style12">BAS</td>
	</tr>
<strong>
	<tr>
		<td colspan="2" class="TSTAB_2">
		<span class="TSIDX___1"><span class="auto-style7">MY COLLECTION OF QBASIC 
		64 PROGRAMS</span><br />
		<br />
		<span class="auto-style7">SOURCECODE<br />
		</span><br />
		MY QB64 PROGRAMS, GITHUB, QB64.ORG<br />
		<br />
		<br />
		<span class="auto-style7">QB64<br />
		</span><br />
		DESCRIPTION: COMMAND-LINE BASED QBASIC IDE, ALL VERSIONS 
		<br />
		DOWNLOAD: <a href="https://qb64.com/" target="_blank">LINK</a></span></td>
	</tr>
	<tr>
		<td colspan="2" class="TSTAB_5">
		<span class="TSIDX___1">
		<a href="DL/ZIP/TS-CODE_QB64.ZIP" target="_blank">DOWNLOAD</a> / ZIP / 
		130 MB</span></td>
	</tr>
</table>
</strong>
</span>
<br class="auto-style4" />
<em><br class="auto-style4" />
</em>
<span class="TSIDX___1">
<table cellpadding="7" cellspacing="0" style="width: 100%" class="auto-style3" align="center">
	<tr>
		<td class="auto-style13">VB6</td>
		<td class="auto-style12">&nbsp;</td>
	</tr>
<strong>
	<tr>
		<td colspan="2" class="TSTAB_2">
		<span class="TSIDX___1"><span class="auto-style7">MY COLLECTION OF VISUAL BASIC PROGRAMS</span><br />
		<br />
		<span class="auto-style7">DOCUMENTS<br />
		</span><br />
		BOOKS IN PDF, HTML, CHM<br />
		<br />
		<span class="auto-style7">SOURCECODE<br />
		</span><br />
		MY VB6 PROGRAMS, GITHUB<br />
		<br />
		<br />
		<span class="auto-style7">VISUAL BASIC 6.0<br />
		</span><br />
		DECRIPTION: VISUAL BASIC 6.0 IDE<br />
		TYPE: ISO<br />
		DOWNLOAD: 
		<a href="https://winworldpc.com/product/microsoft-visual-bas/60" target="_blank">LINK</a></span></td>
	</tr>
	<tr>
		<td colspan="2" class="TSTAB_5">
		<a href="DL/ZIP/TS-CODE_VB6.ZIP" target="_blank">
		<span class="TSIDX___1">
		DOWNLOAD</span></a> / ZIP / 180 MB</td>
	</tr>
</table>
</strong>
</span>
<br class="auto-style4" />
<br class="auto-style4" />
<span class="TSIDX___1">
<table cellpadding="7" cellspacing="0" style="width: 100%" class="auto-style3" align="center">
	<tr>
		<td class="auto-style11" style="width: 44px">
<span class="TSIDX___2">
		WEB</span></td>
		
		<td class="auto-style12">3</td>
	</tr>
<strong>
	<tr>
		<td class="auto-style6" colspan="2"><span class="auto-style7">MY SITE'S 
		ON THE WORLD WIDE WEB<br />
		</span><br />
		DEVELOPED WITH CSS3, HTML4, PHP7<span class="auto-style7"><br />
		</span><br>
		<table cellpadding="5" cellspacing="0" style="width: 100%">
			<tr>
				<td style="width: 20px" valign="top">
<span class="TSIDX___1">
<strong>
		<img src="http://prescene.us.to/favicon.ico" width="16px" height="16px" align="middle"></strong></span></td>
				<td>
<span class="TSIDX___1">
				<a href="HTTP://PRESCENE.US.TO" target="_blank" title="GET SCENE LINKS!">PRESCENE.US.TO</a> - #1 SCENE LINKS IN FILE-SHARING</span></td>
			</tr>
			<tr>
				<td style="width: 20px" valign="top">
<span class="TSIDX___1">
<strong>
		<img src="http://thomasschilb.com/favicon.ico" width="16px" height="16px" align="middle"></strong></span></td>
				<td>
<span class="TSIDX___1">
				<a href="HTTP://THOMASSCHILB.COM" target="_blank">THOMASSCHILB.COM</a> - MY PRIVATE 
				HOMEPAGE</span></td>
			</tr>
			<tr>
				<td style="width: 20px" valign="top">
<span class="TSIDX___1">
<strong>
		<img src="https://ts-records.com/favicon.ico" width="16px" height="16px" align="middle"></strong></span></td>
				<td>
				<a href="HTTP://TS-RECORDS.COM" target="_blank">TS-RECORDS.COM</a> - ELECTRONIC MUSIC PRODUCTION</td>
			</tr>
			</table>
		<br />
		<span class="auto-style8">HTTP/HTTPS IS 
		ON</span><br />
		<br />
		<br />
		<span class="TSIDX___1">
		<span class="auto-style7">NOTEPAD++<br />
		</span><br />
		DESCRIPTION:
		A GOOD CODE-EDITOR IN PLAINTEXT<br />
		DOWNLOAD:
		<a href="https://notepad-plus-plus.org/downloads/" target="_blank">LINK</a><br />
		<br />
		<span class="auto-style7">WEB EXPRESSION 4<br />
		</span><br />
		DESCRIPTION: WYSIWYG EDITOR<br />
		LICENSE: FREE COPY DOWNLOADED FROM MICROSOFT.COM<br />
		DOWNLOAD:
		<a href="./DL/TS-APPS/FREE/MICROSOFT.EXPRESSION.WEB.V4.0-TS.ZIP" target="_blank">
		LINK</a></span></td>
	</tr>
	<tr>
		<td colspan="2" class="TSTAB_5">
		&nbsp;</tr>
</table>
</strong>
</span></p>

</body>

</html>
