<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<meta content="en-us" http-equiv="Content-Language" />
<title>TS | DESIGN</title>
<style type="text/css">
a {
	color: #808080;
	text-decoration: none;
}
a:visited {
	color: #808080;
}
a:active {
	color: #808080;
}
a:hover {
	color: #31C8F9;
}
table {
	font-family:'Roboto Mono Regular', monospace;
	}
}
pre {
	color: #31C8F9;
	}
}
.TS-STYLE_B1 {
	background-color: #333333;
}
.TS-STYLE_B2 {
	color: #31C8F9;
}
.TSIDX___1 {
	font-size: 18px;
}
.TSIDX___2 {
	color: #31C8F9;
	font-size: 18px;
}
.TS-BANNER {
	border-width: 1px;
}
.TSTAB_6 {
	background-color: #333333;
}
.TSTAB_4 {
	background-color: #333333;
	text-align: right;
}
.TSTAB_2 {
	background-color: #181818;
}
.TSTAB_5 {
	background-color: #333333;
	text-align: center;
}
.TSTAB__1 {
	border-collapse: collapse;
	border: 1px solid #333333;
}
.TSTAB__2 {
	border: 1px solid #333333;
}
.auto-style2 {
	font-family: "Roboto Mono Regular", monospace;
}
.auto-style3 {
	border-collapse: collapse;
	border: 1px solid #333333;
	font-family: "Roboto Mono Regular", monospace;
}
.auto-style4 {
	font-size: 18px;
	font-family: "Roboto Mono Regular", monospace;
}
.auto-style5 {
	color: #FFFFFF;
}
.auto-style7 {
	background-color: #000000;
	text-align: right;
}
.auto-style8 {
	background-color: #000000;
	color: #31C8F9;
}
</style>
<meta content="TS, THOMAS, SCHILB, INDEX, PRIVATE, HOMEPAGE, REPOSITORY" name="keywords" />
<meta content="PRIVATE HOMEPAGE" name="description" />
<base target="_self" />
</head>

<body style="color: #808080; margin: 0; background-color: #333333">

<span class="TSIDX___2"><span class="auto-style2">&gt; DESIGN_</span><br /><br /><br />

</span><span class="TSIDX___1">
<table cellpadding="7" cellspacing="0" style="width: 100%" class="auto-style3" align="center">
	<tr>
		<td class="auto-style8">ASCII</td>
		
		<td class="auto-style7">TXT / NFO</td>
	</tr>

	<tr>
		<td colspan="2" class="TSTAB_2">
		<span class="TSIDX___1"><span class="auto-style5">MY COLLECTION OF ASCII ART</span><br />
		<em>
		<br />
		</em><span class="auto-style5">ASCII<br />
		</span><br />
		MY NFO FILES AND LINKS<br />
		<br />
		<br />
		<span class="auto-style5">ASCII ART STUDIO<br />
		</span><br />
		DESCRIPTION: ASCII EDITOR AND CREATOR, STANDARD FONTS<br />
		DOWNLOAD:
		<a href="./DL/TS-APPS/FREE/ASCII.ART.STUDIO.V2.2.1-TS.ZIP" target="_blank">LINK</a><br />
		<br />
		<span class="auto-style5">JANE<br />
		</span><br />
		DESCIPTION: POPULAR NFO EDITOR<br />
		SITE: 
		<a href="https://www.kifoth.de/jane/html/download.php" target="_blank">LINK</a><br />
		<br />
		<span class="auto-style5">JAVE ASCII ART STUDIO<br />
		</span><br />
		DESCRIPTION: ASCII EDITOR AND CREATOR, FIGLET FONTS<br />
		DOWNLOAD:
		<a href="./DL/TS-APPS/FREE/JAVE.V6.0.RC2-TS.ZIP" target="_blank">
		LINK</a></span></td>
	</tr>
	<tr>
		<td colspan="2" class="TSTAB_5">
<a target="_blank" href="DL/ZIP/TS-DESIGN_ASCII.ZIP"><span class="TSIDX___1">DOWNLOAD</span></a> 
		/ ZIP / 3.9 KB</td>
	</tr>
</table>
<br class="auto-style2" />
<br class="auto-style2" />
<table cellpadding="7" cellspacing="0" style="width: 100%" class="auto-style3" align="center">
	<tr>
		<td class="auto-style8">FONTS</td>
		<td class="auto-style7">&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2" class="TSTAB_2">
		<span class="TSIDX___1"><span class="auto-style5">MY COLLECTION OF FONTS</span><br />
		<br />
		<span class="auto-style5">FONTS<br />
		</span><br />
		DESCRIPTION: ASCII FONTS, GOOGLE FONTS. ETC.<br />
		TYPE: FIGLET, FON AND TRUETYPE</span></td>
	</tr>

	<tr>
		<td colspan="2" class="TSTAB_5">
<a target="_blank" href="DL/ZIP/TS-DESIGN_FONTS.ZIP"><span class="TSIDX___1">DOWNLOAD</span></a> <span class="TSIDX___1">
		/ ZIP / 3.8 MB</span></td>
	</tr>
</table>

&nbsp;</span><br class="auto-style4" />
<br class="auto-style4" />
<span class="TSIDX___1">

<table cellpadding="7" cellspacing="0" style="width: 100%" class="auto-style3" align="center">
	<tr>
		<td class="auto-style8">ICONS</td>
		
		<td class="auto-style7">&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2" class="TSTAB_2">
		<span class="TSIDX___1"><span class="auto-style5">MY COLLECTION OF ICONS</span><br />
		<br />
		<span class="auto-style5">ICONSETS<br />
		</span><br />
		MATERIAL-ICONS, REMIXICON, UNICONS,
		TS-ICONS<br />
		<br />
		<span class="auto-style5">INCLUDED<br />
		</span><br />
		ADVANCED BATCH IMAGE CONVERTER, MANY FORMATS<br />
		<br />
		<br />
		<span class="auto-style5">ICON EDITOR PRO 3.6<br />
		</span><br />
		DESCRIPTION: A GOOD ICON EDITOR<br />
		DOWNLOAD:
		<a href="./DL/TS-APPS/PORTABLE/GREENFISH.ICONEDITOR.PRO.V3.6-TS.ZIP">LINK</a></span></td>
	</tr>
	<tr>
		<td colspan="2" class="TSTAB_5">
<a target="_blank" href="DL/ZIP/TS-DESIGN_ICONS.ZIP"><span class="TSIDX___1">DOWNLOAD</span></a> <span class="TSIDX___1">
		/ ZIP / 7.9 MB</span></td>
	</tr>
</table>
</span><br class="auto-style4" />
<br class="auto-style2" />
<span class="TSIDX___1">

<table cellpadding="7" cellspacing="0" style="width: 100%" class="auto-style3" align="center">
	<tr>
		<td class="auto-style8">PICTURES</td>
		<td class="auto-style7">&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2" class="TSTAB_2">
		<span class="TSIDX___1"><span class="auto-style5">MY COLLECTION OF PICTURES</span><br />
		<br />
		<span class="auto-style5">IMAGES<br />
		</span><br />
		GROUPS,
		ME,
		WALLPAPERS,
		XXX<br />
		<br />
		<br />
		<span class="auto-style5">ADOBE PHOTOSHOP CS3<br />
		</span><br />
		DESCRIPTION: MOST POPULAR GRAPHICS ART EDITOR<br />
		DOWNLOAD:
		<a href="./DL/TS-APPS/PORTABLE/ADOBE.PHOTOSHOP.CS3.V10.0-TS.ZIP" target="_blank">LINK</a><br />
		<br />
		<span class="auto-style5">GIMP<br />
		</span><br />
		DESCRIPTION: POPULAR GRAPHICS ART EDITOR<br />
		SITE: <a href="https://www.gimp.org/downloads/" target="_blank">LINK</a></span></td>
	</tr>
	<tr>
		<td colspan="2" class="TSTAB_5">
<a target="_blank" href="DL/ZIP/TS-DESIGN_PICTURES.ZIP"><span class="TSIDX___1">DOWNLOAD</span></a> <span class="TSIDX___1">
		/ ZIP / 35 MB</span></td>
	</tr>
</table>
</span></p>
<span class="auto-style2">&nbsp; </span> <br class="auto-style2" />
<span class="TSIDX___1">


<table cellpadding="7" cellspacing="0" style="width: 100%" class="auto-style3" align="center">
	<tr>
		<td class="auto-style8">SCREENSAVER</td>
		<td class="auto-style7">&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2" class="TSTAB_2">
		<span class="TSIDX___1"><span class="auto-style5">MY COLLECTION OF SCREENSAVER</span><br />
		<br />
		<span class="auto-style5">SCREENSAVER<br />
		</span><br />
		15 OLD AND NEW SCREENSAVERS FOR WINDOWS, SETUP AND SCR-FORMAT</span></td>
	</tr>
	<tr>
		<td colspan="2" class="TSTAB_5">
		<a target="_blank" href="DL/ZIP/TS-DESIGN_SCREENSAVER.ZIP"><span class="TSIDX___1">DOWNLOAD</span></a> <span class="TSIDX___1">
		/ ZIP / 7.4 MB</span></td>
	</tr>
</table>
</span><br class="auto-style2" />


<br class="auto-style4" />
<span class="TSIDX___1">


<table cellpadding="7" cellspacing="0" style="width: 100%" class="auto-style3" align="center">
	<tr>
		<td class="auto-style8">SKINS</td>
		<td class="auto-style7">&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2" class="TSTAB_2">
		<span class="TSIDX___1"><span class="auto-style5">MY COLLECTION OF WINAMP SKINS</span><br />
		<br />
		<span class="auto-style5">CONTENT<br />
		</span><br />
		MY WINAMP 2.X SKINS AND SOME OTHER<br />
		<br />
		<br />
		<span class="auto-style5">QMMP<br />
		</span><br />
		DESCRITION: FREE AUDIO PLAYER, MANY FORMATS<br />
		SITE: <a href="https://qmmp.ylsoftware.com/" target="_blank">LINK</a><br />
		<br />
		<span class="auto-style5">WINAMP 2.95<br />
		</span><br />
		DESCRIPTION: POPULAR AUDIO PLAYER, MANY FORMATS WITH MANY<br />
		VISUALTIZATIONS, SKINS AND EXTRAS<br />
		DOWNLOAD:
		<a href="DL/TS-APPS/FREE/WINAMP.V2.95-TS.ZIP" target="_blank">LINK</a></span></td>
	</tr>
	<tr>
		<td colspan="2" class="TSTAB_5">
		<a target="_blank" href="DL/ZIP/TS-DESIGN_SKINS.ZIP"><span class="TSIDX___1">DOWNLOAD</span></a> <span class="TSIDX___1">
		/ ZIP / 11 MB</span></td>
	</tr>
</table>
</span>

</body>

</html>
