<title>TS Computing - Kontakt</title>
<p><span class="auto-style7">
EMAIL/TODO/ABUSE</span><br class="auto-style4" />
<br class="auto-style4" />
<span class="auto-style4"><a href="mailto:THOMASSCHILB@WEB.DE">
THOMASSCHILB@WEB.DE</a> </span><br class="auto-style4" />
<br />
<br>SMS/MMS<br><br>+491727707269<br><br>
<br class="auto-style4" />
<span class="auto-style7">
MEDIA</span><br class="auto-style4" />
<br class="auto-style4" />
<span class="auto-style4">
<a target="_blank" href="https://www.deviantart.com/schilb">DEVIANTART</a></span><br class="auto-style4" />
<span class="auto-style4">
<a target="_blank" href="https://www.facebook.com/thomas.schilb.14/">FACEBOOK</a></span><br class="auto-style4" />
<span class="auto-style4">
<a href="https://github.com/thomasschilb-dev" target="_blank">GITHUB</a></span><br class="auto-style4" />
<span class="auto-style4">
<a target="_blank" href="https://soundcloud.com/thomasschilb">SOUNDCLOUD</a></span><br class="auto-style4" />
<span class="auto-style4">
<a href="https://twitter.com/thomasschilb23" target="_blank">TWITTER</a></span><br class="auto-style4" />
<span class="auto-style4">
<a target="_blank" href="https://www.youtube.com/channel/UCi1VCoKxngXVwGqyVVHIEqA">YOUTUBE</a></span><br class="auto-style4" />
<br class="auto-style4" />
<br class="auto-style4" />
<span class="auto-style7">
SUPPORT</span><br class="auto-style4" />
<br class="auto-style4" />
<span class="auto-style4">
<a href="https://apachefriends.org/" target="_blank">APACHE FRIENDS</a><br />
<a href="https://github.com/" target="_blank">GITHUB</a></span><br class="auto-style4" />
<span class="auto-style4">
<a href="https://google.com" target="_blank">GOOGLE</a></span><br class="auto-style4" />
<span class="auto-style4">
<a href="https://microsoft.com" target="_blank">MICROSOFT</a></span></p>



