
<head>
<style type="text/css">
.auto-style1 {
	color: #31C8F9;
}
</style>
</head>

<title>TS Computing - &#220;ber Uns</title>
<span class="auto-style9"><p>WIR</span><span class="auto-style16"> SIND EINE JUNGE ARBEITSGEMEINSCHAFT</span><br class="auto-style16" />
<span class="auto-style16">IM BEREICH
IT &amp; COMPUTING,
IN KOOPERATION</span><br class="auto-style16" />
<span class="auto-style16">MIT MEHREREN NETZWERKEN WELTWEIT.</p></span><p class="auto-style16">
<span class="TS-CONTACT1"><span class="auto-style16"><br />
<span class="auto-style1"><strong>&bull;</strong></span></span></span><span class="auto-style17"> MITGLIEDER</span><br class="auto-style16" />
<br class="auto-style16" />
<span class="auto-style16">THOMAS SCHILB</span><br class="auto-style16" />
<br class="auto-style16" />
<span class="auto-style16">CODE</span><span class="auto-style15"> PHP, QB64</span><span class="TS-CONTACT2"><br class="auto-style16" />
<span class="auto-style16">GFX</span></span><span class="auto-style15"> PHOTOSHOP</span><span class="TS-CONTACT2"><br class="auto-style16" />
<span class="auto-style16">SND</span></span><span class="auto-style15"> FL STUDIO</span><span class="TS-CONTACT2"><br class="auto-style16" />
<span class="auto-style16">SYSOP</span></span><span class="auto-style15"> VSERVER, STRATO AG<br />
</span></p>
<p class="auto-style16">
<em><br>HOSTED IN GERMANY/DE_DE BY
</em>
<a href="https://www.strato.de/" target="_blank" title="BESUCHE STRATO AG AUF WWW.STRATO.DE">
<em>STRATO AG</em></a></p>
