<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<meta content="en-us" http-equiv="Content-Language" />
<title>TS | CONTACT</title>
<style type="text/css">
a {
	color: #808080;
	text-decoration: none;
}
a:visited {
	color: #808080;
}
a:active {
	color: #808080;
}
a:hover {
	color: #31C8F9;
}
.TS-CONTACT1 {
	color: #31C8F9;
}
.TS-CONTACT2 {
	color: #FFFFFF;
}
.TSIDX___1 {
	font-size: 18px;
}
.auto-style4 {
	font-family: "Roboto Mono Regular", monospace;
}
.auto-style6 {
	font-size: 23px;
	font-family: "Roboto Mono Regular", monospace;
	color: #31C8F9;
}
.auto-style7 {
	font-family: "Roboto Mono Regular", monospace;
	color: #FFFFFF;
}
.auto-style8 {
	font-family: "Roboto Mono Regular", monospace;
	font-size: 23px;
}
.auto-style9 {
	font-family: "Roboto Mono Regular", monospace;
	color: #FFFFFF;
	font-size: 23px;
}
.auto-style10 {
	font-size: 23px;
}
</style>
<meta content="TS, THOMAS, SCHILB, INDEX, PRIVATE, HOMEPAGE, REPOSITORY" name="keywords" />
<meta content="PRIVATE HOMEPAGE" name="description" />
<base target="_self" />
</head>

<body style="color: #808080; margin: 0; background-color: #333333">

<span class="auto-style6">&gt; KONTAKT_</span><p>
<span class="auto-style9">
<br />
MEDIA</span><br class="auto-style8" />
<br class="auto-style8" />
<span class="auto-style8">
<a target="_blank" href="https://www.deviantart.com/schilb">DEVIANTART</a></span><br class="auto-style8" />
<span class="auto-style8">
<a target="_blank" href="https://www.facebook.com/thomas.schilb.14/">FACEBOOK</a></span><br class="auto-style8" />
<span class="auto-style4">
<a href="https://github.com/thomasschilb-dev" target="_blank">
<span class="auto-style10">GITHUB</span></a><br class="auto-style10" />
<a href="https://www.linkedin.com/in/thomasschilb/" target="_blank">
<span class="auto-style10">LINKEDIN</span></a></span><br class="auto-style8" />
<span class="auto-style8">
<a target="_blank" href="https://soundcloud.com/thomasschilb">SOUNDCLOUD</a></span><br class="auto-style8" />
<span class="auto-style8">
<a href="https://twitter.com/thomasschilb23" target="_blank">TWITTER</a></span><br class="auto-style8" />
<span class="auto-style8">
<a target="_blank" href="https://www.youtube.com/channel/UCi1VCoKxngXVwGqyVVHIEqA">YOUTUBE</a></span><br />
</p>
<p>
<span class="auto-style7">
<span class="auto-style10"><br />
E-MAIL <a href="mailto:THOMAS_SCHILB@OUTLOOK.COM">THOMAS_SCHILB@OUTLOOK.COM</a></span></span><br />
</p>
<p>
<span class="auto-style7">
<span class="auto-style10"><br />
SMS/MMS</span></span><span class="auto-style8"> 
+491727707296</span></p>

</body>

</html>
