<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<meta content="en-us" http-equiv="Content-Language" />
<title>TS | THOMAS SCHILB</title>
<style type="text/css">
a {
	color: #808080;
	text-decoration: none;
}
a:visited {
	color: #808080;
}
a:active {
	color: #808080;
}
a:hover {
	color: #31C8F9;
}
table {
	font-family:'Roboto Mono Regular', monospace;
	}
}
pre {
	color: #31C8F9;
	}
}
.TS-STYLE_B1 {
	background-color: #333333;
}
.TS-STYLE_B2 {
	color: #31C8F9;
}
.TSIDX___1 {
	font-size: 18px;
}
.TSIDX___2 {
	color: #31C8F9;
	font-size: 18px;
}
.auto-style5 {
	font-family: "Roboto Mono Regular", monospace;
}
.auto-style7 {

}
.TS-CONTACT2 {

}
.auto-style8 {
	font-size: 20px;
}
.auto-style9 {
	color: #31C8F9;
	font-size: 23px;
}
.auto-style4 {
	font-family: "Roboto Mono Regular", monospace;
	font-size: 23px;
}
.auto-style10 {
	font-size: 23px;
}
.auto-style11 {
	font-family: "Roboto Mono Regular", monospace;
	font-size: 23px;
}
.auto-style12 {
	color: #FFFFFF;
}
.auto-style14 {
	font-family: "Roboto Mono Regular", monospace;
	font-size: 23px;
	color: #808080;
}
</style>
<meta content="TS, THOMAS, SCHILB, INDEX, PRIVATE, HOMEPAGE, REPOSITORY" name="keywords" />
<meta content="PRIVATE HOMEPAGE" name="description" />
<base target="_self" />
</head>

<body style="color: #808080; margin: 0; background-color: #333333">

<span class="auto-style9"><span class="auto-style5">&gt; SERVICE_</span></span><span class="auto-style5"><span class="auto-style10"><p class="auto-style14">
WIR SIND BEREITS FÜR FOLGENDE FIRMEN IN 3<br />
VERSCHIEDENEN BEREICHEN FÜR SIE TÄTIG...</p>
</span>
<span class="auto-style7">
<p>
<span class="auto-style4">
<span class="TS-STYLE_B2">
<br />
&bull; </span>
<span class="auto-style7">
<span class="auto-style12">ENTWICKLUNG</span><br />
<br />
	</span>
	</span>
<span class="auto-style7">
<span class="auto-style5">
<span class="auto-style10">
<span class="auto-style12">DATENBANKEN</span></span></span></span></span><span class="auto-style8"><span class="auto-style5"><span class="auto-style10"> POSTGRESQL, MYSQL<span class="auto-style7"><br />
<span class="auto-style12">PROGRAMMIERSPRACHEN</span></span> PHP, 
		JSP, QB64<span class="auto-style7"><br />
<span class="auto-style12">WEB-ENTWICKLUNG</span></span> LOGIN, UI, CONTENT<br />
</span></span><span class="auto-style7"><br />
</p>
<p class="auto-style11">

</span><span class="auto-style4">
<span class="TS-STYLE_B2">
&bull; </span>
<span class="auto-style7">
<span class="TS-CONTACT2">
<span class="auto-style12">SYSTEM ADMINISTRATION</span><br />
<br />

</span>

</span>
	</span>

<span class="auto-style4">
<em>SOFTWARE INSTALLATION, 
		KONFIGURATION UND WARTUNG INKL. BACKUP</em><span class="auto-style7"><span class="TS-CONTACT2"><br />
<br />
<span class="auto-style12">BETRIEBSSYSTEME</span></span></span> DEBIAN, WINDOWS SERVER<span class="TS-CONTACT2"><span class="auto-style7"><br />
<span class="auto-style12">WEB-ENTWICKLUNG</span></span></span> LOGIN, UI, CONTENT<span class="auto-style7"><span class="TS-CONTACT2"><br />
<span class="auto-style12">WEBSERVER</span></span></span> APACHE2<br />
</span><span class="auto-style7"><br />
</p>

</span></span></span>

<p class="auto-style4"><span class="TS-STYLE_B2">&bull; </span>
<span class="auto-style12">NETZWERKSICHERHEIT</span><br />
<br />
<span class="auto-style12">VERSCHLÜSSELUNG</span> SSL, SSH<br />
<span class="auto-style12">WLAN</span> EINRICHTUNG UND KONFIGURATION<br />
</p>
<p class="auto-style4">TODO? <a href="https://www.linkedin.com/in/thomasschilb" target="_blank">THOMASSCHILB@LINKEDIN.COM</a></p>

</body>

</html>
