<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<meta content="en-us" http-equiv="Content-Language" />
<title>TS | NFO</title>
<style type="text/css">
a {
	color: #808080;
	text-decoration: none;
}
a:visited {
	color: #808080;
}
a:active {
	color: #808080;
}
a:hover {
	color: #31C8F9;
}
.TS-CONTACT1 {
	color: #31C8F9;
}
.TS-CONTACT2 {
	color: #FFFFFF;
}
.TSIDX___1 {
	font-size: 18px;
}
.auto-style4 {
	font-family: "Roboto Mono Regular", monospace;
	font-size: 18px;
}
.auto-style6 {
	font-size: 23px;
	font-family: "Roboto Mono Regular", monospace;
	color: #31C8F9;
}
.auto-style5 {
	font-family: "Roboto Mono Regular", monospace;
}
.auto-style7 {
	font-family: "Roboto Mono Regular", monospace;
	font-size: 20px;
}
.auto-style9 {
	font-size: 23px;
}
.auto-style10 {
	font-family: "Roboto Mono Regular", monospace;
	font-size: 23px;
}
</style>
<meta content="TS, THOMAS, SCHILB, INDEX, PRIVATE, HOMEPAGE, REPOSITORY" name="keywords" />
<meta content="PRIVATE HOMEPAGE" name="description" />
<base target="_self" />
</head>

<body style="color: #808080; margin: 0; background-color: #333333">

<span class="auto-style6">&gt; ÜBERUNS</span><span class="TS-CONTACT1">_</span><span class="auto-style5"><p class="auto-style10">
<span class="auto-style9">WIR</span><span class="auto-style10"> SIND EINE JUNGE ARBEITSGEMEINSCHAFT<br />
IM BEREICH
IT &amp; COMPUTING,
IN KOOPERATION<br />
MIT MEHREREN NETZWERKEN WELTWEIT.</span></p>
<p class="auto-style10">
<span class="TS-CONTACT1"><br />
&bull;</span><span class="TS-CONTACT2"> MITGLIEDER</span><br />
<br />
<span class="TS-CONTACT2">THOMAS SCHILB<br />
<br />
CODE</span> PHP, QB64<span class="TS-CONTACT2"><br />
GFX</span> PHOTOSHOP<span class="TS-CONTACT2"><br />
SND</span> FL STUDIO<span class="TS-CONTACT2"><br />
SYSOP</span> VSERVER, STRATO AG<br />
<br />
</p>
<span class="auto-style4"><span class="auto-style7">
<p><span class="auto-style4">
<span class="auto-style10">
<em>HOSTED IN GERMANY/DE_DE BY
</em>
<a href="https://www.strato.de/" target="_blank" title="BESUCHE STRATO AG AUF WWW.STRATO.DE">
<em>STRATO AG</em></a></span></span></p>

</span>
</span>

</span>

</body>

</html>
