<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<meta content="en-us" http-equiv="Content-Language" />
<title>TS | NFO</title>
<style type="text/css">
a {
	color: #808080;
	text-decoration: none;
}
a:visited {
	color: #808080;
}
a:active {
	color: #808080;
}
a:hover {
	color: #31C8F9;
}
.TS-CONTACT1 {

}
.TS-CONTACT2 {
	color: #FFFFFF;
}
.TSIDX___1 {
	font-size: 18px;
}
.auto-style6 {
	font-size: 23px;
	font-family: "Roboto Mono Regular", monospace;
	color: #31C8F9;
}
.auto-style7 {
	font-family: "Roboto Mono Regular", monospace;
	font-size: 23px;
}
.auto-style8 {
	
}
</style>
<meta content="TS, THOMAS, SCHILB, INDEX, PRIVATE, HOMEPAGE, REPOSITORY" name="keywords" />
<meta content="PRIVATE HOMEPAGE" name="description" />
<base target="_self" />
</head>

<body style="color: #808080; margin: 0; background-color: #333333">

<span class="auto-style6">&gt; IMPRESSUM_</span><span class="TS-CONTACT1"><p>

<span class="auto-style7">
<br />
</span>
</span>

<span class="auto-style7">
TS AG<br />
LYONER STR. 1<br />
60528, NIEDERRAD<br />
<br />
E-MAIL: 
<span class="TS-CONTACT1"> 
<a href="mailto:THOMASSCHILB@WEB.DE?subject=ABUSE" title="FEEL FREE TO SEND COMPLAINTS OR SUGGESTIONS FOR IMPROVEMENT">THOMASSCHILB@WEB.DE</a><br />
</span>STID-NR.: 67858029419<span class="TS-CONTACT1"><br />
</span></span></p>
<p><span class="auto-style7">
<span class="TS-CONTACT1">
<span class="TS-CONTACT2"><br />
WEBSITE</span><br />
<br />
</span>DIESES IMPRESSUM GILT FÜR ALLE ANGEBOTE UNTER DER DOMAIN 
<span class="TS-CONTACT1"> 
<a href="http://WWW.TSAG.IO">WWW.TSAG.IO</a><br />
</span>INKLUSIVE 
ALLER SUBDOMAINS (UNTERSEITEN).<span class="TS-CONTACT1"><br />
</span></span><span class="TS-CONTACT1"></p>
<p>
</span><span class="auto-style7">
<span class="TS-CONTACT1"><span class="TS-CONTACT2"><br />
SOZIALE MEDIEN</span><br />
<br />
</span>DIESES IMPRESSUM GILT AUCH FÜR UNSERE AUFTRITTE IN DEN FOLGENDEN<br />
SOZIALEN 
MEDIEN (ANGABEN GEMÄß § 5 TMG):<br />
<br />
LINKEDIN: <span class="TS-CONTACT1"> <a href="HTTPS://WWW.LINKEDIN.COM/IN/THOMASSCHILB/" title="TODO?">HTTPS://WWW.LINKEDIN.COM/IN/THOMASSCHILB/</a></span></span><span class="TS-CONTACT1"></p>
<p><span class="auto-style7">
<span class="TS-CONTACT2"><br />
BERUFLICHE ANGABEN</span><br />
</span>
</span><span class="auto-style7">
<br />
<span class="auto-style8">BERUFSBEZEICHNUNG: FREELANCER<br />
VERLIEHEN IN: DEUTSCHLAND<br />
BERUFSRECHTLICHE REGELUNGEN:
TRAINEE, FREELANCER</span></span><span class="TS-CONTACT1"><br />
</p>
<span class="TS-CONTACT1">
<p><span class="auto-style7">
<span class="TS-CONTACT2"><br />
GÜLTIGKEIT</span><br />
<br />
</span>
</span>
</span><span class="auto-style7">
DIESES IMPRESSUM GILT AB DEM 17. OKTOBER 2023.<br />
</span></p>
<span class="TS-CONTACT1">
<p>
</span><span class="auto-style7">
<span class="TS-CONTACT1">
<span class="TS-CONTACT2"><br />
STREITBEILEGUNG</span><br />
<br />
</span>WIR BEMÜHEN UNS JEDERZEIT UM EIN EINVERNEHMEN MIT DEM KUNDEN.<br />
NUTZEN SIE UNSEREN SERVICEKONTAKT UNTER <span class="TS-CONTACT1"> <a href="mailto:THOMASSCHILB@WEB.DE">THOMASSCHILB@WEB.DE</a></span><br />
ODER UNSERE WEITEREN ANGEGEBENEN KONTAKTMÖGLICHKEITEN.<span class="TS-CONTACT1"><br />
<br />
</span>DIE EUROPÄISCHE KOMMISSION STELLT EINE PLATTFORM ZUR<br />
ONLINE-STREITBEILEGUNG (OS) MIT WEITEREN INFORMATIONEN ZUR<br />
VERFÜGUNG,
DIE IM INTERNET UNTER:<span class="TS-CONTACT1"><br />
<br />
<a href="https://ec.europa.eu/consumers/odr/" target="_blank">
HTTPS://EC.EUROPA.EU/CONSUMERS/ODR/</a></span> ERREICHBAR IST.<span class="TS-CONTACT1"><br />
<br />
WIR SIND NICHT BEREIT UND NICHT VERPFLICHTET, AN EINEM<br />
STREITBEILEGUNGSVERFAHREN
VOR EINER<br />
VERBRAUCHERSCHLICHTUNGSSTELLE TEILZUNEHMEN.</span></span><span class="TS-CONTACT1"><span class="TS-CONTACT1"><span class="TS-CONTACT1"><span class="TS-CONTACT1"></p>
</span>
</span>
</span>
</span>

</body>

</html>
