<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
<meta content="en-us" http-equiv="Content-Language" />
<title>TS | MUSIC</title>
<style type="text/css">
a {
	color: #808080;
	text-decoration: none;
}
a:visited {
	color: #808080;
}
a:active {
	color: #808080;
}
a:hover {
	color: #31C8F9;
}
table {
	font-family:'Roboto Mono Regular', monospace;
	}
}
pre {
	color: #31C8F9;
	}
}
.TS-STYLE_B1 {
	background-color: #333333;
}
.TS-STYLE_B2 {
	color: #31C8F9;
}
.TSIDX___1 {
	font-size: 18px;
}
.TSIDX___2 {
	color: #31C8F9;
	font-size: 18px;
}
.TSTAB_6 {
	background-color: #333333;
}
.TSTAB_4 {
	background-color: #333333;
	text-align: right;
}
.TSTAB_2 {
	background-color: #181818;
}
.TSTAB_5 {
	background-color: #333333;
	text-align: center;
}
.TSTAB__1 {
	border-collapse: collapse;
	border: 1px solid #333333;
}
.auto-style3 {
	border-collapse: collapse;
	border: 1px solid #333333;
	font-family: "Roboto Mono Regular", monospace;
}
.auto-style4 {
	font-size: 18px;
	font-family: "Roboto Mono Regular", monospace;
}
.auto-style5 {
	font-family: "Roboto Mono Regular", monospace;
}
.auto-style6 {
	color: #31C8F9;
	font-size: 18px;
	font-family: "Roboto Mono Regular", monospace;
}
.auto-style7 {
	color: #FFFFFF;
}
.auto-style9 {
	background-color: #000000;
	text-align: right;
}
.auto-style10 {
	background-color: #000000;
	color: #31C8F9;
}
.auto-style11 {
	background-color: #000000;
}
</style>
<meta content="TS, THOMAS, SCHILB, INDEX, PRIVATE, HOMEPAGE, REPOSITORY" name="keywords" />
<meta content="PRIVATE HOMEPAGE" name="description" />
<base target="_self" />
</head>

<body style="color: #808080; margin: 0; background-color: #333333">

<span class="auto-style6">&gt; MUSIC_<br />
</span><br class="auto-style4" />
<br class="auto-style5" />
<span class="TSIDX___1">

<table cellpadding="7" cellspacing="0" style="width: 100%" class="auto-style3" align="center">
	<tr>
		<td class="auto-style10">MODULES</td>
		<td class="auto-style9">&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2" class="TSTAB_2" style="height: 114px">
		<span class="TSIDX___1"><span class="auto-style7">MY COLLECTION OF MODULES</span><br />
		<br />
		<span class="auto-style7">MODULES<br />
		</span><br />
		DESCRIPTION: TOTAL OF 43 GROUPS WITH 1400+ CHIPTUNES<em><br />
		<br />
		</em>GROUPS: ACME, AGAiN, AiR, BLiZZARD, BRD, CHAOS!, CHiCNCREAM, CLASS,
		CORE, CRUDE, DEViANCE, DJiNN, DVT, ECLiPSE, EiTheL, EMBRACE,
		EPSiLON, F4CG, FAiRLiGHT, FFF, H2O, HERiTAGE, HOODLUM, KaOs,
		LUCiD, Lz0, MESMERiZE, MYTH, ORiON, PARADOX, Postmortem, R2R,
		Razor1911, Reloaded, REPT, SHOCK, SKiDROW, SnD, TSRh, uCF,
		X-FORCE, ZENiTH, ZWT<br />
		<br />
		FORMAT: MOD, XM, ETC.<br />
		<br />
		<br />
		<span class="auto-style7">VLC<br />
		</span><br />
		DESCRIPTION: POPULAR AUDIO PLAYER<br />
		SITE: <a href="https://www.videolan.org/vlc/" target="_blank">LINK</a></span></td>
	</tr>
	<tr>
		<td colspan="2" class="TSTAB_5">
<a target="_blank" href="DL/ZIP/TS-MUSIC_MODULES.ZIP"><span class="TSIDX___1">DOWNLOAD</span></a> <span class="TSIDX___1">
		/ ZIP / 72 MB</span></td>
	</tr>
</table>
<br class="auto-style5" />
<br />

<table cellpadding="7" cellspacing="0" style="width: 100%" class="auto-style3" align="center">
	<tr>
		<td class="auto-style11"><span class="TSIDX___2">

		SAMPLES</span></td>
		<td class="auto-style9">&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2" class="TSTAB_2" style="height: 114px">
<span class="TSIDX___1">

		<span class="auto-style7">MY COLLECTION OF SAMPLES</span><br />
		<br />
		<span class="auto-style7">ONE-SHOTS<br />
		</span><br />
		DESCRIPTION: A TOTAL OF 6900+ ONE SHOTS, BIG COLLECTION<br />
		<br />
		CATEGORIES: BASS, BEAT, CHORD, CLAP, CRASH, CYMBAL, EXTRA,<br />
		FX, GLITCH, GROOVE, HIHAT, KICK, LEAD, LOW, MICRO, NOISE,<br />
		PADS, PERC, RIDE, ROLL, SHAKER, SNARE, SYNTH, TOM,<br />
		UPGATED, UPGRADE, VOCAL<br />
		<br />
		FORMAT: .WAV<br />
		GENRE: TECHNO, MINIMAL, ETC.<br />
		SOURCE: TS, WEB<br />
		USAGE: DAW OR TRACKER<br />
		<br />
		<br />
		<span class="auto-style7">LMMS<br />
		</span><br />
		DESCRIPTION: A GOOD FREE DAW!<br />
		SITE: <a href="https://lmms.io/" target="_blank">LINK</a></span></td>
	</tr>
	<tr>
		<td colspan="2" class="TSTAB_5">
<a target="_blank" href="DL/ZIP/TS-MUSIC_MODULES.ZIP"><span class="TSIDX___1">DOWNLOAD</span></a> <span class="TSIDX___1">
		/ ZIP / 1.5 GB</span></td>
	</tr>
</table>
<br />
</span>
<br class="auto-style4" />
<span class="TSIDX___1">

<table cellpadding="7" cellspacing="0" style="width: 100%" class="auto-style3" align="center">
	<tr>
		<td class="auto-style10">TRACKS</td>
		
		<td class="auto-style9">&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2" class="TSTAB_2">
		<span class="TSIDX___1"><span class="auto-style7">MY COLLECTION OF SONGS</span><br />
		<br />
		<span class="auto-style7">GENRE<br />
		</span><br />
		HIPHOP, MISC, OLDIES, RAP, ROCK &amp; TECHNO<br />
		<br />
		<br />
		<span class="auto-style7">NEED A GOOD PLAYER?<br />
		<br />
		</span>SITE:
		<a target="_blank" href="https://www.videolan.org/vlc/" target="_blank">VLC</a>,
		<a href="https://www.winamp.com/player/downloads/" target="_blank">
		WINAMP</a>,
		<a href="https://www.thomasschilb.com/DL/TS-APPS/FREE/WINAMP.V2.95-TS.ZIP" target="_blank">
		WINAMP 2.95</a></span></td>
	</tr>
	<tr>
		<td colspan="2" class="TSTAB_5">
<a target="_self" href="#"><span class="TSIDX___1">DOWNLOAD</span></a> <span class="TSIDX___1">
		/ ZIP / 1.1 GB</span></td>
	</tr>
</table>
</span>
<p>&nbsp;</p>

</body>

</html>
